### ISSUE TITLE
release upgrade

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/lmfdb-gce#4]
Release upgrade all instances to 16 LTS.

ps: I'm in no rush.

**Comment by sarunasb** [comment]
www-central1 upgraded to 16.04.1. Can be tested individually as 

[http://www-central1.lmfdb.xyz](http://www-central1.lmfdb.xyz)

**Comment by edgarcosta** [comment]
Great thank you!

**Comment by sarunasb** [comment]
Testupgrade of ms1 was uneventfull (MongoDB start had to be switched from upstart to systemd). Assuming it's safe to upgrade ms.

**Comment by edgarcosta** [comment]
I would leave ms for last, as it the only one that isn't relunctant.
My order would be:
- arb
- m0
- warwick
- ms

**Comment by sarunasb** [comment]
arb, m0, warwick upgraded (OS and MongoDB). No disasters in logs. beta.lmfdb.org seems alive, but checks only superficial.

Let me know if/when it's OK to upgrade ms and www-central0.

**Comment by edgarcosta** [comment]
You can go ahead and upgrade www-central0.

For ms, please take this into account
https://github.com/edgarcosta/lmfdb-gce/blob/master/doc/maintenace_on_ms.md

Thank you.

**Comment by sarunasb** [comment]
All on 16.04.1.
